apiVersion: apps/v1
kimd: Deployment
metadata:
  name: prometheus
  namespace:  fleet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app:  prometheus
    spec:
      containers:
        - name: prometheus
          image:  prom/prometheus:latest
          ports:
            - containerPort:  9090
          resources:
            requests:
              memory: "256Mi"
              cpu:  "250m"
            limits:
              memory: "512Mi"
              cpu:  "500m"

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace:  fleet
spec:
  selector:
    app:  prometheus
  ports:
    - port: 9090
      targetPort: 9090